#!/bin/bash
# Helper script para rebuilder el devcontainer con Docker support

echo "🔄 Instrucciones para Rebuild del Dev Container"
echo "=============================================="
echo ""
echo "Para activar Docker en tu devcontainer, necesitas hacer un rebuild:"
echo ""
echo "📝 Método 1 - Command Palette (Recomendado):"
echo "   1. Presiona Ctrl+Shift+P (Cmd+Shift+P en Mac)"
echo "   2. Busca: 'Dev Containers: Rebuild Container'"
echo "   3. Selecciona la opción y espera"
echo ""
echo "📝 Método 2 - Desde terminal del host:"
echo "   1. Abre terminal en tu máquina local"
echo "   2. Navega al directorio del proyecto" 
echo "   3. Ejecuta: code . --rebuild"
echo ""
echo "⏱️  El rebuild tomará unos minutos..."
echo ""
echo "✅ Después del rebuild, verifica Docker:"
echo "   docker --version"
echo "   docker-compose --version"
echo "   docker ps"
echo ""
echo "🐳 Una vez listo, puedes construir la imagen MCP:"
echo "   docker build -t mcp-azure-devops ."
echo "   ./scripts/test-container.sh"
echo ""
echo "💡 Tip: El socket Docker del host (/var/run/docker.sock) será"
echo "   montado automáticamente en el container."
